#!/usr/bin/python3
import argparse, json

parser = argparse.ArgumentParser()
parser.add_argument('action', help='select an action (list, new, describe, finish, archive, delete)')
parser.add_argument('-n', '--name', help='task name')
parser.add_argument('-d', '--desc', help='task description')
parser.add_argument('-a', '--all', action='store_true', help='show all including finished tasks')
args = parser.parse_args()
db={}

try:
    with open('db', 'r') as db_file:
        db = json.load(db_file)
except FileNotFoundError:
    print('warning: db file not found. creating new db...')
    open('db','w').write('{}')

if args.action == 'list':
    print('{0:50}  {1}'.format('task','status'))
    for task in db:
        if args.all or db[task]['status'] != 'finished':
            print('{0:50}  {1}'.format(task, db[task]['status']))
elif args.action == 'new':
    db[args.name] = {
            'name': args.name,
            'description': args.desc,
            'status': 'not started',
    }
elif args.action == 'finish':
    db[args.name]['status'] = 'finished'
elif args.action == 'delete':
    del db[args.name]

with open('db', 'w') as db_file:
    json.dump(db, db_file)
